In [1]:
import pandas as pd 
import numpy as np

In [5]:
# Display Dataset

house_data = pd.read_csv("house Prediction Data Set(Raw data).csv")
house_data.head(5)

  0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
0   0.02731   0.00   7.070  0  0.4690  6.4210  78...
1   0.02729   0.00   7.070  0  0.4690  7.1850  61...
2   0.03237   0.00   2.180  0  0.4580  6.9980  45...
3   0.06905   0.00   2.180  0  0.4580  7.1470  54...
4   0.02985   0.00   2.180  0  0.4580  6.4300  58...

In [7]:
# Separate column properly
house_data = pd.read_csv(
    "house Prediction Data Set(Raw data).csv",
    sep=r"\s+",
    header=None
)

In [7]:
# Display Dataset
house_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [8]:
# Data types
print(house_data.dtypes)

0     float64
1     float64
2     float64
3       int64
4     float64
5     float64
6     float64
7     float64
8       int64
9     float64
10    float64
11    float64
12    float64
13    float64
dtype: object

In [9]:
# Check missing values
missing_values = house_data.isnull().sum()
print(missing_values)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
dtype: int64

In [10]:
# Duplicate rows
print("Duplicate rows:", house_data.duplicated().sum())

Duplicate rows: 0

In [11]:
house_data.to_csv("Cleaned_house_Dataset.csv", index=False)